class BPError(Exception):...
class BPNotConvergedError(BPError):...

class BubbleConError(Exception): ...

class ITEError(Exception):...
class TensorNetworkError(Exception): ...
class NetworkConnectionError(TensorNetworkError): ...

class LatticeError(Exception): ...
class DirectionError(Exception): ...
class OutsideLatticeError(LatticeError): ...